version: '3.3'

services:
  unit:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: unit
    command: [ "/bin/sh", "-c", "npm start" ]
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8085:8085
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
